# Generated by Django 3.0 on 2021-08-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_user', '0002_auto_20210824_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ushou',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
