# Generated by Django 3.0 on 2021-08-29 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cb_goods', '0005_auto_20210829_0551'),
        ('cb_user', '0003_userinfo_ushou'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cb_goods.GoodsInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cb_user.UserInfo')),
            ],
        ),
    ]
