# Generated by Django 3.0 on 2021-08-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_star', '0002_starinfo_sdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starinfo',
            name='sdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
