# Generated by Django 3.0 on 2021-08-24 08:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gtitle', models.CharField(max_length=40)),
                ('gpic', models.ImageField(upload_to='cb_goods')),
                ('gprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gsellprice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('isDelete', models.BooleanField(default=False)),
                ('gauthor', models.CharField(max_length=20)),
                ('gpublish', models.CharField(max_length=20)),
                ('gpubtime', models.CharField(max_length=20)),
                ('gclick', models.IntegerField()),
                ('gbrief', models.CharField(max_length=200)),
                ('gstock', models.IntegerField()),
                ('gcontent', tinymce.models.HTMLField()),
                ('gtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cb_goods.TypeInfo')),
            ],
        ),
    ]
