# Generated by Django 3.0 on 2021-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_goods', '0002_auto_20210824_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinfo',
            name='gauthor',
            field=models.CharField(max_length=80),
        ),
    ]
