# Generated by Django 3.0 on 2021-08-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_goods', '0003_auto_20210824_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gdiscount',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=2),
        ),
    ]
