# Generated by Django 3.0 on 2021-08-29 05:51

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_goods', '0004_goodsinfo_gdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gauthorIntroduct',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gcatalogue',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goodsinfo',
            name='gdetail',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
